"""auto update

Revision ID: 531e475c2c73
Revises: 856507d89109
Create Date: 2026-10-08 20:48:45.388158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '531e475c2c73'
down_revision: Union[str, Sequence[str], None] = '856507d89109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('jd_id', sa.Integer(), nullable=False),
    sa.Column('resume_text', sa.String(), nullable=False),
    sa.Column('gaps', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gap_analyses_id'), 'gap_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_gap_analyses_jd_id'), 'gap_analyses', ['jd_id'], unique=False)
    op.create_index(op.f('ix_gap_analyses_user_id'), 'gap_analyses', ['user_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('jd_id', sa.Integer(), nullable=False),
    sa.Column('gap_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('abilities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('gaps', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('abilities_examined', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('abilities_remaining', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('current_ability_id', sa.String(), nullable=True),
    sa.Column('dialogue', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('round_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_current_ability_id'), 'interview_sessions', ['current_ability_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_gap_id'), 'interview_sessions', ['gap_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_id'), 'interview_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_jd_id'), 'interview_sessions', ['jd_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    op.create_table('jd_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('jd_text', sa.String(), nullable=False),
    sa.Column('abilities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_analyses_id'), 'jd_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_jd_analyses_user_id'), 'jd_analyses', ['user_id'], unique=False)
    op.create_table('knowledge_marks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tech_id', sa.Integer(), nullable=False),
    sa.Column('tech_name', sa.String(), nullable=True),
    sa.Column('mastery', sa.String(), nullable=True),
    sa.Column('favorited', sa.Boolean(), nullable=True),
    sa.Column('personal_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_marks_id'), 'knowledge_marks', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_marks_tech_id'), 'knowledge_marks', ['tech_id'], unique=False)
    op.create_index(op.f('ix_knowledge_marks_user_id'), 'knowledge_marks', ['user_id'], unique=False)
    op.create_table('knowledge_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('definition', sa.String(), nullable=True),
    sa.Column('key_points', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('common_exam_points', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('related_technologies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('feedback_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_points_id'), 'knowledge_points', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_points_id'), table_name='knowledge_points')
    op.drop_table('knowledge_points')
    op.drop_index(op.f('ix_knowledge_marks_user_id'), table_name='knowledge_marks')
    op.drop_index(op.f('ix_knowledge_marks_tech_id'), table_name='knowledge_marks')
    op.drop_index(op.f('ix_knowledge_marks_id'), table_name='knowledge_marks')
    op.drop_table('knowledge_marks')
    op.drop_index(op.f('ix_jd_analyses_user_id'), table_name='jd_analyses')
    op.drop_index(op.f('ix_jd_analyses_id'), table_name='jd_analyses')
    op.drop_table('jd_analyses')
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_jd_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_gap_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_current_ability_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_gap_analyses_user_id'), table_name='gap_analyses')
    op.drop_index(op.f('ix_gap_analyses_jd_id'), table_name='gap_analyses')
    op.drop_index(op.f('ix_gap_analyses_id'), table_name='gap_analyses')
    op.drop_table('gap_analyses')
    # ### end Alembic commands ###