"""auto update

Revision ID: 7a9ed134e7e0
Revises: 4e37a7065af4
Create Date: 2026-10-08 21:12:26.378456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a9ed134e7e0'
down_revision: Union[str, Sequence[str], None] = '4e37a7065af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_points', sa.Column('doc', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_points', 'doc')
    # ### end Alembic commands ###